import Head from 'next/head';
import { ChangeEventHandler, useState } from 'react';

export default function Home() {
  const [textAreaValue, setTextAreaValue] = useState('');

  const handleChangeTextAreaValue: ChangeEventHandler<HTMLTextAreaElement> = ({ target }) => {
    const { value } = target;

    setTextAreaValue(value);
  };

  const handleReplaceNbsp = () => {
    const replacedNbsp = textAreaValue.replace(/&nbsp;/g, ' ');

    setTextAreaValue(replacedNbsp);
  };
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <textarea value={textAreaValue} onChange={handleChangeTextAreaValue} />
        <button type="button" onClick={handleReplaceNbsp}>
          변환하기
        </button>
      </main>
    </>
  );
}
